name: papco_shop
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  dio: ^5.4.0
  bloc: ^8.1.2
  shimmer: ^3.0.0
  equatable: ^2.0.5
  go_router: ^13.0.1
  animate_do: ^3.1.2
  flutter_bloc: ^8.1.3
  google_fonts: ^6.1.0
  url_launcher: ^6.1.14
  cupertino_icons: ^1.0.6
  responsive_sizer: ^3.2.0
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  flutter_custom_clippers: ^2.1.0
  page_view_dot_indicator: ^2.3.0


  flutter:
    sdk: flutter
  gap: ^3.0.1
  flutter_localizations:
    sdk: flutter
  carousel_slider: ^4.2.1
  flutter_riverpod: ^2.4.9
  intl: ^0.18.1
  connectivity_plus: ^5.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/intro/
    - assets/images/amazing/




  fonts:
    - family: normal
      fonts:
        - asset: assets/fonts/IRAN-Sans-Regular.ttf

    - family: bold
      fonts:
        - asset: assets/fonts/IRAN-Sans-Bold.ttf
